Models/PageContent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IndianArmyWeb.Models
{
    public class PageContent
    {
        [Key]
        public int PageContentId { get; set; }
        
        [Column(TypeName = "ntext")]
        public string Content { get; set; }

        public int MenuId { get; set; }
        public virtual MenuItemMaster MenuItemMasters { get; set; }
    }
}

Areas/cpanel/Controllers/PageContentController.cs
using IndianArmyWeb.DataContexts;
using IndianArmyWeb.Persistence;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using AutoMapper;
using System.IO;
using IndianArmyWeb.Models;
using IndianArmyWeb.Areas.cpanel.View_Models;
using IndianArmyWeb.Infrastructure.Helpers.Routing;
using IndianArmyWeb.Infrastructure.Constants;
using IndianArmyWeb.Infrastructure.Helpers.FileDirectory;
using IndianArmyWeb.Infrastructure.Helpers.Editor;
using IndianArmyWeb.Infrastructure.Helpers.Account;
using IndianArmyWeb.Infrastructure.Filters;
using IndianArmyWeb.Infrastructure.Extensions;

namespace IndianArmyWeb.Areas.cpanel.Controllers
{
  
    [SessionTimeout]
    [Authorize]
    [CSPLHeaders]
    public class PageContentController : Controller
    {
        // GET: PageContent
        public async Task<ActionResult> Index()
        {
            UserActivityHelper.SaveUserActivity("Page List Accessed", Request.Url.ToString());
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                int roleid = UserAccountHelper.getCurrentUserRoleId();
                var MenuRole = uow.MenuRoleRepo.Find(x => x.RoleId == roleid && x.Read == true).Select(x => x.MenuId);
                var pageContent = uow.PageContentRepo.Find(x => MenuRole.Contains(x.MenuId));
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<IEnumerable<PageContent>, List<PageContentIndxVM>>();
                });
                IMapper mapper = config.CreateMapper();
                var indexDto = mapper.Map<IEnumerable<PageContent>, IEnumerable<PageContentIndxVM>>(pageContent).ToList();
                await uow.CommitAsync();
                return View(indexDto);
            }
        }

        // GET: PageContent/Create
        public async Task<ActionResult> Create()
        {
            UserActivityHelper.SaveUserActivity("Page Create Option visited", Request.Url.ToString());
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                int roleid = UserAccountHelper.getCurrentUserRoleId();
                var MenuRole = uow.MenuRoleRepo.Find(x => x.RoleId == roleid && x.Write == true).Select(x => (x.MenuId).ToString());
                var ParentMenus = uow.MenuItemMstrRepo.GetParentMenus();
                ViewBag.ParentMenus = ParentMenus.Where(x => MenuRole.Contains(x.Value));
                await uow.CommitAsync();
                return View();
            }
        }

        // POST: PageContent/Create
        [ValidateInput(false)]
        [HttpPost]
        public async Task<ActionResult> Create(PageContentCrtVM objPageContCvm)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<PageContentCrtVM, PageContent>();
                });
                IMapper mapper = config.CreateMapper();
                PageContent CreateDto = mapper.Map<PageContentCrtVM, PageContent>(objPageContCvm);
                uow.PageContentRepo.Add(CreateDto);
                await uow.CommitAsync();
                this.AddNotification("Page saved", NotificationType.SUCCESS);
                return RedirectToAction("Create");
            }
        }

        // GET: PageContent/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                int roleid = UserAccountHelper.getCurrentUserRoleId();
                var MenuRole = uow.MenuRoleRepo.Find(x => x.RoleId == roleid && x.Write == true).Select(x => (x.MenuId).ToString());
                var ParentMenus = uow.MenuItemMstrRepo.GetParentMenus();
                ViewBag.ParentMenus = ParentMenus.Where(x => MenuRole.Contains(x.Value));
                var pgContntMstr = uow.PageContentRepo.GetByIdAsync(id);
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<PageContent, PageContentUpVM>();
                });
                IMapper mapper = config.CreateMapper();
                PageContentUpVM UpdateDto = mapper.Map<PageContent, PageContentUpVM>(await pgContntMstr);
                await uow.CommitAsync();
                return View(UpdateDto);
            }
        }

        // POST: PageContent/Edit/5
        [ValidateInput(false)]
        [HttpPost]
        public async Task<ActionResult> Edit(PageContentUpVM objPageContUvm)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<PageContentUpVM, PageContent>();
                });
                IMapper mapper = config.CreateMapper();
                PageContent UpdateDTO = mapper.Map<PageContentUpVM, PageContent>(objPageContUvm);
                uow.PageContentRepo.Update(UpdateDTO);
                await uow.CommitAsync();
                this.AddNotification("Page updated", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<JsonResult> DeleteOnConfirm(int id)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var dataModal = await uow.PageContentRepo.GetByIdAsync(id);
                if (dataModal == null)
                {
                    return Json(data: "Not Deleted", behavior: JsonRequestBehavior.AllowGet);
                }
                else
                {
                    uow.PageContentRepo.Remove(dataModal);
                    await uow.CommitAsync();
                    return Json(data: "Deleted", behavior: JsonRequestBehavior.AllowGet);
                }
            }
        }
        public async Task<ActionResult> PagePreview(int id)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var pageContent = await uow.PageContentRepo.GetByIdAsync(id);
                ViewBag.Content = pageContent.Content;
                await uow.CommitAsync();
                return View();
            }
        }

        [HttpPost]
        public ActionResult ImageUpload(HttpPostedFileBase file)
        {
            string currentYear = DateTime.Now.Year.ToString();
            string currentMonth = DateTime.Now.ToString("MMM");
            string path = Path.Combine(ServerRootConsts.NEWS_CONTENT_ROOT, "images", currentYear, currentMonth);
            var location = TinyEditorHelper.SaveImageFile(Server.MapPath(path), file, path);
            return Json(new { location }, JsonRequestBehavior.AllowGet);
        }
    }
}

Areas/cpanel/Views/PageContent/Create.cshtml
@model IndianArmyWeb.Areas.cpanel.View_Models.PageContentCrtVM

@{
    ViewBag.Title = "Create Pages";
}

<div class="main-card mb-3 card">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <h5 class="card-title">@ViewBag.Title</h5>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.MenuId, "Menu Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MenuId", (IEnumerable<SelectListItem>)ViewBag.ParentMenus, "Select", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MenuId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", @rows="50" } })*@
                    @Html.TextAreaFor(model => model.Content, new { @class = "form-control editorHtml" })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '#Content',
            mode: "textareas",
            height: 1000,
            plugins: "code,autolink,image,imagetools,media,link,lists,pagebreak,style,table,advhr,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,searchreplace,print,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template, wordcount, advlist, autosave, visualblocks",
            images_reuse_filename: true,
            image_title: true,
            images_upload_url: '@Url.Action("ImageUpload")',
            relative_urls: false,
        });
    </script>
}

Areas/cpanel/Views/PageContent/Edit.cshtml
@model IndianArmyWeb.Areas.cpanel.View_Models.PageContentUpVM

@{
    ViewBag.Title = "Edit";
}

<div class="main-card mb-3 card">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.PageContentId)

        <div class="card-body">
            <h5 class="card-title">Edit Page (s)</h5>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @*@Html.LabelFor(model => model.MenuId, "Menu Name", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-12">
                    @Html.DropDownList("MenuId", (IEnumerable<SelectListItem>)ViewBag.ParentMenus, "Select", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MenuId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @*@Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-12">
                    @Html.TextAreaFor(model => model.Content, new { @class = "form-control editorHtml" })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-primary" />
                </div>
            </div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '#Content',
            mode: "textareas",
            height: 1000,
            //width: 600,
            plugins: "code,autolink,image,imagetools,media,link,lists,pagebreak,style,table,advhr,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,searchreplace,print,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template, wordcount, advlist, autosave, visualblocks",
            images_reuse_filename: true,
            image_title: true,
            images_upload_url: '@Url.Action("ImageUpload")',
            relative_urls: false,
        });
    </script>
}

Areas/cpanel/Views/PageContent/Index.cshtml
@model IEnumerable<IndianArmyWeb.Areas.cpanel.View_Models.PageContentIndxVM>

@{
    ViewBag.Title = "Index";
}
<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">List of Page (s)</h5>
        <div class="pull-right">
            <a href="@Url.Action("Create","PageContent")" class="btn-shadow mb-3 mt-0 btn btn-primary">Create Page</a>
        </div>
        <table class="mb-0 table table-hover table-bordered tab w-100" id="myTable">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.MenuItemMasters.SlugMenu)
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.Content)
                    </th>*@
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MenuItemMasters.SlugMenu)
                        </td>
                        @*<td>
                            @Html.Raw(item.Content)
                        </td>*@
                        <td>
                            <a href="@Url.Action("Edit", new { id = item.PageContentId })"><i class="fa fa-edit"></i></a>
                            <a href="@Url.Action("PagePreview", new { id = item.PageContentId })" target="_blank"><i class="fa fa-eye"></i></a>
                            <button type="button" class="btn btn-transparent red btn-xs" onclick="Delete(@item.PageContentId, this)"><i class="fa fa-trash"></i></button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script>
    LoadJDT('#myTable');

    function Delete(id, event) {
        var TableId = "#myTable";
        var Jsonurl = '@Url.Action("DeleteOnConfirm")';
        DeleteJDTRow(id, event, TableId, Jsonurl)
    }
    </script>
}

Areas/cpanel/Views/PageContent/PagePreview.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "PagePreview";
}

<!-- Home About Start Here -->
<div class="about-featured">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h2 class="title2">Page Preview </h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                @if (ViewBag.Content != null)
                {
                    @Html.Raw(ViewBag.Content as string);
                }
            </div>

        </div>
    </div>
</div>
<!-- Home About End Here -->