Models/MenuItemMaster.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using IndianArmyWeb.Infrastructure.Constants;

namespace IndianArmyWeb.Models
{
    public class MenuItemMaster
    {
        [Key]
        public int MenuId { get; set; }
        public int ParentId { get; set; }
        public string SlugMenu { get; set; }
        public int SortOrder { get; set; }
        public string MenuName { get; set; }
        public string HMenuName { get; set; }
        public string PageTitle { get; set; }
        public string PageHeading { get; set; }
        public string HPageHeading { get; set; }
        public bool IsVisible { get; set; }
        public PositionType PositionType { get; set; }
        public Layout Layout { get; set; }
        public bool ExternalLink { get; set; }
        public string ExternalUrl { get; set; }
        public int? MenuUrlId { get; set; }
        public virtual MenuUrlMaster MenuUrlMasters { get;set;}
        

        //public string HPageTitle { get; set; }
        //public string MenuPrefix { get; set; }
        //public int TempleteId { get; set; }
        //public bool Active { get; set; }
        //public int Menutype { get; set; }
    }
}

Areas/cpanel/Controllers/MenuItemMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using IndianArmyWeb.Persistence;
using IndianArmyWeb.DataContexts;
using IndianArmyWeb.Areas.cpanel.View_Models;
using IndianArmyWeb.Models;
using AutoMapper;
using IndianArmyWeb.Infrastructure.Filters;
using IndianArmyWeb.Infrastructure.Helpers.Menu;
using IndianArmyWeb.Infrastructure.Helpers.Account;
using IndianArmyWeb.Infrastructure.Extensions;

namespace IndianArmyWeb.Areas.cpanel.Controllers
{
    [UserMenuAttribute]
    [Authorize]
    [CSPLHeaders]
    [SessionTimeout]
    public class MenuItemMasterController : Controller
    {
        // GET: MenuItemMaster
        public async Task<ActionResult> Index()
        {
            UserActivityHelper.SaveUserActivity("Menu Master Page Accessed", Request.Url.ToString());
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var menuItmMstr = await uow.MenuItemMstrRepo.GetAllAsync();
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<IEnumerable<MenuItemMaster>, List<MenuItemMasterIndxVM>>();
                });
                IMapper mapper = config.CreateMapper();
                var indexDto = mapper.Map<IEnumerable<MenuItemMaster>, IEnumerable<MenuItemMasterIndxVM>>(menuItmMstr).ToList();
                await uow.CommitAsync();
                return View(indexDto);
            }
        }

        // GET: MenuItemMaster/Create
        public async Task<ActionResult> Create()
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                ViewBag.ParentMenus = uow.MenuItemMstrRepo.GetParentMenus();
                ViewBag.UrlPrefixs = uow.MenuUrlMstrRepo.GetUrlPrefixs();
                await uow.CommitAsync();
                return View();
            }
        }

        // POST: MenuItemMaster/Create
        [HttpPost]
        public async Task<ActionResult> Create(MenuItemMasterCrtVM objMenuItmMstrCvm)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<MenuItemMasterCrtVM, MenuItemMaster>();
                });
                IMapper mapper = config.CreateMapper();
                MenuItemMaster CreateDto = mapper.Map<MenuItemMasterCrtVM, MenuItemMaster>(objMenuItmMstrCvm);
                uow.MenuItemMstrRepo.Add(CreateDto);
                await uow.CommitAsync();
                this.AddNotification("Data saved", NotificationType.SUCCESS);
                return RedirectToAction("Create");
            }
        }

        // GET: MenuItemMaster/Edit/5
        public ActionResult Edit(int id)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                ViewBag.ParentMenus = uow.MenuItemMstrRepo.GetParentMenus();
                ViewBag.UrlPrefixs = uow.MenuUrlMstrRepo.GetUrlPrefixs();

                var menuItemMstr = uow.MenuItemMstrRepo.GetById(id);
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<MenuItemMaster, MenuItemMasterUpVM>();
                });
                IMapper mapper = config.CreateMapper();
                MenuItemMasterUpVM UpdateDto = mapper.Map<MenuItemMaster, MenuItemMasterUpVM>(menuItemMstr);
                uow.Commit();
                return View(UpdateDto);
            }
        }

        // POST: MenuItemMaster/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(MenuItemMasterUpVM objMenuItemUvm)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<MenuItemMasterUpVM, MenuItemMaster>();
                });
                IMapper mapper = config.CreateMapper();
                MenuItemMaster UpdateDto = mapper.Map<MenuItemMasterUpVM, MenuItemMaster>(objMenuItemUvm);
                uow.MenuItemMstrRepo.Update(UpdateDto);
                await uow.CommitAsync();
                this.AddNotification("Data updated", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
        }
        public async Task<ActionResult> MenuSortOrder()
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                ViewBag.menus = uow.MenuItemMstrRepo.GetParentMenus();
                await uow.CommitAsync();
                return View();
            }
        }
        [HttpPost]
        public ActionResult MenuSortOrder(int[] menuIds)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                int sortorder = 1;
                foreach (int id in menuIds)
                {
                    MenuItemMaster menuitem = uow.MenuItemMstrRepo.GetById(id);
                    menuitem.SortOrder = sortorder;

                    uow.MenuItemMstrRepo.UpdateMenuSortOrder(menuitem);
                    uow.Commit();
                    sortorder += 1;
                }
                //return View(uow.MenuItemMstrRepo.GetAll().OrderBy(p => p.SortOrder).ToList());
                return RedirectToAction("MenuSortOrder");
            }
        }
        [HttpPost]
        public JsonResult GetMenuSortData(int menuId)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var menuSortData = uow.MenuItemMstrRepo.Find(x => x.ParentId == menuId).OrderBy(x=>x.SortOrder);
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<IEnumerable<MenuItemMaster>, List<MenuSortOrderVM>>();
                });
                IMapper mapper = config.CreateMapper();
                var data = mapper.Map<IEnumerable<MenuItemMaster>, IEnumerable<MenuSortOrderVM>>(menuSortData).ToList();
                uow.Commit();
                return Json(data, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public async Task<JsonResult> DeleteOnConfirm(int id)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var dataModal = await uow.MenuItemMstrRepo.GetByIdAsync(id);
                if (dataModal == null)
                {
                    return Json(data: "Not Deleted", behavior: JsonRequestBehavior.AllowGet);
                }
                else
                {
                    uow.MenuItemMstrRepo.Remove(dataModal);
                    await uow.CommitAsync();
                    UserActivityHelper.SaveUserActivity("Menu Deleted", Request.Url.ToString());
                    return Json(data: "Deleted", behavior: JsonRequestBehavior.AllowGet);
                }
            }
        }
        //[HttpGet]
        //public ActionResult JsTreeDemo()
        //{
        //    return View();
        //}
        public ActionResult Nodes()
        {
            var nodes = TreeViewHelper.GetMenuTree().ToList();
            return Json(nodes, JsonRequestBehavior.AllowGet);
        }
        
    }
}

Areas/cpanel/Views/MenuItemMaster/Create.cshtml
@model IndianArmyWeb.Areas.cpanel.View_Models.MenuItemMasterCrtVM

@{
    ViewBag.Title = "Create Menu";
}
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <div id="html1">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="main-card mb-3 card">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="card-body">
                    <h5 class="card-title">Create Menu Item (s)</h5>
                    <hr />
                    @*<form>*@
                    <div class="form-group">
                        @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                        @Html.DropDownList("ParentId", (IEnumerable<SelectListItem>)ViewBag.ParentMenus, "Select", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MenuName, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                        @Html.EditorFor(model => model.MenuName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.HMenuName, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                        @Html.EditorFor(model => model.HMenuName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HMenuName, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PageTitle, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                        @Html.EditorFor(model => model.PageTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PageTitle, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PageHeading, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                        @Html.EditorFor(model => model.PageHeading, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PageHeading, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.HPageHeading, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                        @Html.EditorFor(model => model.HPageHeading, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HPageHeading, "", new { @class = "text-danger" })
                    </div>
                    <div class="position-relative row form-group">
                        @Html.LabelFor(model => model.PositionType, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                        <div class="col-md-2">
                            @Html.EnumDropDownListFor(model => model.PositionType, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PositionType, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.Layout, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                        <div class="col-md-2">
                            @Html.EnumDropDownListFor(model => model.Layout, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Layout, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.MenuUrlId, "Section", htmlAttributes: new { @class = "col-sm-1 col-form-label" })
                        <div class="col-md-2">
                            @Html.DropDownList("MenuUrlId", (IEnumerable<SelectListItem>)ViewBag.UrlPrefixs, null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MenuUrlId, "", new { @class = "text-danger" })
                        </div>
                        <div class="custom-checkbox custom-control">
                            @Html.EditorFor(model => model.IsVisible, new { htmlAttributes = new { @class = "col-sm-2 custom-control-input" } })
                            @Html.LabelFor(model => model.IsVisible, htmlAttributes: new { @class = "custom-control-label" })
                            @Html.ValidationMessageFor(model => model.IsVisible, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="position-relative row form-group">
                        @Html.LabelFor(model => model.ExternalUrl, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.ExternalUrl, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="custom-checkbox custom-control">
                            @Html.EditorFor(model => model.ExternalLink, new { htmlAttributes = new { @class = "col-sm-2 custom-control-input" } })
                            @Html.LabelFor(model => model.ExternalLink, htmlAttributes: new { @class = "custom-control-label" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="mb-2 mr-2 btn btn-primary" />
                        </div>
                    </div>
                </div>
                }
            </div>

        </div>
        </div>



        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")

            <script>
                LoadMenuTreeView('#html1', '/MenuItemMaster/Nodes');
                ChangeMenuTreeView('#html1', '#ParentId');
            </script>
        }

Areas/cpanel/Views/MenuItemMaster/Edit.cshtml
@model IndianArmyWeb.Areas.cpanel.View_Models.MenuItemMasterUpVM

@{
    ViewBag.Title = "Edit";
}

    <div class="main-card mb-3 card">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.MenuId)
            @Html.HiddenFor(model => model.SortOrder)

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="card-body">
            <h5 class="card-title">Create Menu Item (s)</h5>
            <hr />
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.DropDownList("ParentId", (IEnumerable<SelectListItem>)ViewBag.ParentMenus, "Select", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                </div>
            </div><div class="position-relative row form-group">
                @Html.LabelFor(model => model.MenuName, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MenuName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.HMenuName, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HMenuName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HMenuName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.PageTitle, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PageTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PageTitle, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.PageHeading, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PageHeading, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PageHeading, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.HPageHeading, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HPageHeading, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HPageHeading, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.PositionType, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-2">
                    @Html.EnumDropDownListFor(model => model.PositionType, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PositionType, "", new { @class = "text-danger" })
                </div>
                @Html.LabelFor(model => model.Layout, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-2">
                    @Html.EnumDropDownListFor(model => model.Layout, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Layout, "", new { @class = "text-danger" })
                </div>
                @Html.LabelFor(model => model.MenuUrlId, "Section", htmlAttributes: new { @class = "col-sm-1 col-form-label" })
                <div class="col-md-2">
                    @Html.DropDownList("MenuUrlId", (IEnumerable<SelectListItem>)ViewBag.UrlPrefixs, null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MenuUrlId, "", new { @class = "text-danger" })
                </div>
                <div class="custom-checkbox custom-control">
                    @Html.EditorFor(model => model.IsVisible, new { htmlAttributes = new { @class = "col-sm-2 custom-control-input" } })
                    @Html.LabelFor(model => model.IsVisible, htmlAttributes: new { @class = "custom-control-label" })
                    @Html.ValidationMessageFor(model => model.IsVisible, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.ExternalUrl, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.ExternalUrl, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="custom-checkbox custom-control">
                    @Html.EditorFor(model => model.ExternalLink, new { htmlAttributes = new { @class = "col-sm-2 custom-control-input" } })
                    @Html.LabelFor(model => model.ExternalLink, htmlAttributes: new { @class = "custom-control-label" })
                </div>
            </div>
            <div class="position-relative row form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="mb-2 mr-2 btn btn-primary" />
                </div>
            </div>
        </div>
        }
    </div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/cpanel/Views/MenuItemMaster/Index.cshtml
@model IEnumerable<IndianArmyWeb.Areas.cpanel.View_Models.MenuItemMasterIndxVM>

@{
    ViewBag.Title = "List of Menus";
}

<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">List of Menu Item (s)</h5>
        <div class="pull-right">
            <a href="@Url.Action("Create","MenuItemMaster")" class="btn-shadow mb-3 mt-0 btn btn-primary">Create Menu</a>
        </div>
        <table class="mb-0 table table-hover table-bordered tab w-100" id="myTable">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ParentId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MenuName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HMenuName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PageTitle)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PageHeading)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HPageHeading)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsVisible)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SlugMenu)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PositionType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Layout)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MenuUrlId)
                    </th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ParentId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MenuName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HMenuName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PageTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PageHeading)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HPageHeading)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsVisible)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SlugMenu)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PositionType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Layout)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MenuUrlId)
                        </td>
                        <td>
                            <a href="@Url.Action("Edit", new { id = item.MenuId })"><i class="fa fa-edit"></i></a>
                            <button type="button" class="btn btn-transparent red btn-xs" onclick="Delete(@item.MenuId, this)"><i class="fa fa-trash"></i></button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts {
    <script>
    LoadJDT('#myTable');

    function Delete(id, event) {
        var TableId = "#myTable";
        var Jsonurl = '@Url.Action("DeleteOnConfirm")';
        DeleteJDTRow(id, event, TableId, Jsonurl)
    }
    </script>
}

Areas/cpanel/Views/MenuItemMaster/MenuSortOrder.cshtml
@model IndianArmyWeb.Areas.cpanel.View_Models.MenuSortOrderVM

@{
    ViewBag.Title = "Manage Menu Appearence";

}
<div class="row">
    <div class="col-lg-12">
        <div class="main-card mb-3 card">
            <div class="card-header">Manage Menu Appearence</div>
            <div class="card-body">
                @using (Html.BeginForm())
                {

                <div class="position-relative row form-group">
                    <div class="col-sm-10">
                        @Html.DropDownList("Menu_Id", (IEnumerable<SelectListItem>)ViewBag.menus, "Select Parent Menu", htmlAttributes: new { @class = "dropdown-toggle-split dropdown-toggle btn btn-success" })
                        @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        <input type="submit" value="Update Sorting" class="mb-2 mr-2 btn btn-primary" />
                    </div>
                </div>
                    <hr />
                    <div class="col-md-8">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <table id="tblLocations" class="table table-borderless">
                            <tbody></tbody>
                        </table>
                    </div>
                }

            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/themes/smoothness/jquery-ui.css" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#Menu_Id").change(function () {
                GetSortDataTbl();
            })
        })
        function GetSortDataTbl() {
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetMenuSortData")',
                dataType: "JSON",
                data: { menuId: $("#Menu_Id").val() },
                success: function (data) {
                    var tablesTb = $('#tblLocations tbody');
                    tablesTb.empty();
                    var a = 0;
                    $.each(data, function (i, menudt) {
                        a++;

                        tablesTb.append('<tr><td style="visibility:hidden;">' + a.toString() + '</td><td style="visibility:hidden;">' + menudt.MenuId + '<input type="hidden;" name="menuIds" value=' + menudt.MenuId + '></input></td><td style="cursor: move;border-style: dotted; !important" class="main-card mb-1 card">' + menudt.MenuName + '</td><td style="visibility:hidden;">' + menudt.SortOrder + '</td></tr>');
                    });
                    SortCss();
                },
                error: function (ex) {
                    alert('Failed to retrieve Data.');
                }
            });
        }
    </script>
    <script type="text/javascript">
        function SortCss() {
            $("#tblLocations").sortable({
                //items: 'tr:not(tr:first-child)',
                items: 'tr:not(thead tr)',
                cursor: 'pointer',
                axis: 'y',
                dropOnEmpty: false,
                start: function (e, ui) {
                    ui.item.addClass("selected");
                },
                stop: function (e, ui) {
                    ui.item.removeClass("selected");
                },
                receive: function (e, ui) {
                    $(this).find("tbody").append(ui.item);
                }
            });
        }
    </script>
}