Models/NewsArticle.cs
using IndianArmyWeb.Infrastructure.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IndianArmyWeb.Models
{
    public class NewsArticle : BaseEntity
    {
        [Key]
        public int NewsArticleId { get; set; }
        public NewsCategory NewsCategory { get; set; }
        public string Headline { get; set; }

        [Column(TypeName = "ntext")]
        public string Description { get; set; }
        public bool Highlight { get; set; }
        public bool Archive { get; set; }
        public DateTime PublishDate { get; set; }
        public DateTime ArchiveDate { get; set; }
        
    }
}

Areas/cpanel/Controllers/NewsArticleController.cs
using AutoMapper;
using IndianArmyWeb.Areas.cpanel.View_Models;
using IndianArmyWeb.DataContexts;
using IndianArmyWeb.Infrastructure.Constants;
using IndianArmyWeb.Infrastructure.Extensions;
using IndianArmyWeb.Infrastructure.Filters;
using IndianArmyWeb.Infrastructure.Helpers.Editor;
using IndianArmyWeb.Models;
using IndianArmyWeb.Persistence;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IndianArmyWeb.Areas.cpanel.Controllers
{
    [CSPLHeaders]
    [SessionTimeout]
    [Authorize]
    public class NewsArticleController : Controller
    {
        // GET: NewsArticle
        public async Task<ActionResult> Index()
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var newsArticle = await uow.NewsArticleRepo.GetAllAsync();
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<IEnumerable<NewsArticle>, List<NewsArticleIndxVM>>();
                });
                IMapper mapper = config.CreateMapper();
                var indexDto = mapper.Map<IEnumerable<NewsArticle>, IEnumerable<NewsArticleIndxVM>>(newsArticle).ToList();
                await uow.CommitAsync();
                return View(indexDto);
            }
        }

        // GET: NewsArticle/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewsArticle/Create
        [ValidateInput(false)]
        [HttpPost]
        public async Task<ActionResult> Create(NewsArticleCrtVM objNewsArtclCvm)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<NewsArticleCrtVM, NewsArticle>();
                });
                IMapper mapper = config.CreateMapper();
                NewsArticle CreateDto = mapper.Map<NewsArticleCrtVM, NewsArticle>(objNewsArtclCvm);
                uow.NewsArticleRepo.Add(CreateDto);
                await uow.CommitAsync();
                this.AddNotification("Data saved", NotificationType.SUCCESS);
                return RedirectToAction("Create");
            }
        }

        // GET: NewsArticle/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var newsArticle = await uow.NewsArticleRepo.GetByIdAsync(id);
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<NewsArticle, NewsArticleUpVM>();
                });
                IMapper mapper = config.CreateMapper();
                NewsArticleUpVM UpdateDto = mapper.Map<NewsArticle, NewsArticleUpVM>(newsArticle);
                uow.Commit();
                return View(UpdateDto);
            }
        }

        // POST: NewsArticle/Edit/5
        [ValidateInput(false)]
        [HttpPost]
        public async Task<ActionResult> Edit(NewsArticleUpVM objNewsArtclUvm)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<NewsArticleUpVM, NewsArticle>();
                });
                IMapper mapper = config.CreateMapper();
                NewsArticle UpdateDto = mapper.Map<NewsArticleUpVM, NewsArticle>(objNewsArtclUvm);
                uow.NewsArticleRepo.Update(UpdateDto);
                await uow.CommitAsync();
                this.AddNotification("Data updated", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<JsonResult> DeleteOnConfirm(int id)
        {
            using (var uow = new UnitOfWork(new IASiteContext()))
            {
                var DeleteItem = await uow.NewsArticleRepo.GetByIdAsync(id);
                if (DeleteItem == null)
                {
                    return Json(data: "Not Deleted", behavior: JsonRequestBehavior.AllowGet);
                }
                else
                {
                    uow.NewsArticleRepo.Remove(DeleteItem);
                    await uow.CommitAsync();
                    return Json(data: "Deleted", behavior: JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult ImageUpload(HttpPostedFileBase file)
        {
            string currentYear = DateTime.Now.Year.ToString();
            string currentMonth = DateTime.Now.ToString("MMM");
            string path = Path.Combine(ServerRootConsts.NEWS_CONTENT_ROOT, "images", currentYear, currentMonth);
            var location = TinyEditorHelper.SaveImageFile(Server.MapPath(path), file, path);
            return Json(new { location }, JsonRequestBehavior.AllowGet);
        }
    }
}

Areas/cpanel/Views/NewsArticle/Create.cshtml
@model IndianArmyWeb.Areas.cpanel.View_Models.NewsArticleCrtVM

@{
    ViewBag.Title = "Create Article";
}

<div class="main-card mb-3 card">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="card-body">
            <h5 class="card-title">@ViewBag.Title</h5>
            <hr />
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.NewsCategory, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-2">
                    @Html.EnumDropDownListFor(model => model.NewsCategory, "-- Select --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NewsCategory, "", new { @class = "text-danger" })
                </div>
                @Html.LabelFor(model => model.Headline, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Headline, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Headline, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control datepickerCss1", @autocomplete="off" } })
                    @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
                </div>
                @Html.LabelFor(model => model.ArchiveDate, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.ArchiveDate, new { htmlAttributes = new { @class = "form-control datepickerCss1", @autocomplete="off" } })
                    @Html.ValidationMessageFor(model => model.ArchiveDate, "", new { @class = "text-danger" })
                </div>
                <div class="custom-checkbox custom-control">
                    @Html.EditorFor(model => model.Highlight, new { htmlAttributes = new { @class = "col-sm-1 custom-control-input" } })
                    @Html.LabelFor(model => model.Highlight, htmlAttributes: new { @class = "custom-control-label col-md-12" })
                    @Html.ValidationMessageFor(model => model.Highlight, "", new { @class = "text-danger" })
                </div>
                <div class="custom-checkbox custom-control">
                    @Html.EditorFor(model => model.Archive, new { htmlAttributes = new { @class = "col-sm-1 custom-control-input" } })
                    @Html.LabelFor(model => model.Archive, htmlAttributes: new { @class = "custom-control-label" })
                    @Html.ValidationMessageFor(model => model.Archive, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="mb-2 mr-2 btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '#Description',
            mode: "textareas",
            height: 400,
            //width: 600,
            plugins: "code,autolink,image,imagetools,media,link,lists,pagebreak,style,table,advhr,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,searchreplace,print,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template, wordcount, advlist, autosave, visualblocks",
            images_reuse_filename: true,
            image_title: true,
            images_upload_url: '@Url.Action("ImageUpload")',
            relative_urls: false,
        });
    </script>
}

Areas/cpanel/Views/NewsArticle/Edit.cshtml
@model IndianArmyWeb.Areas.cpanel.View_Models.NewsArticleUpVM

@{
    ViewBag.Title = "Edit";
}

<div class="main-card mb-3 card">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.NewsArticleId)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="card-body">
            <h5 class="card-title">@ViewBag.Title</h5>
            <hr />
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.NewsCategory, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-2">
                    @Html.EnumDropDownListFor(model => model.NewsCategory, "-- Select --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NewsCategory, "", new { @class = "text-danger" })
                </div>
                @Html.LabelFor(model => model.Headline, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Headline, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Headline, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control datepickerCss1", @autocomplete="off" } })
                    @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
                </div>
                @Html.LabelFor(model => model.ArchiveDate, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.ArchiveDate, new { htmlAttributes = new { @class = "form-control datepickerCss1", @autocomplete="off" } })
                    @Html.ValidationMessageFor(model => model.ArchiveDate, "", new { @class = "text-danger" })
                </div>
                <div class="custom-checkbox custom-control">
                    @Html.EditorFor(model => model.Highlight, new { htmlAttributes = new { @class = "col-sm-1 custom-control-input" } })
                    @Html.LabelFor(model => model.Highlight, htmlAttributes: new { @class = "custom-control-label col-md-12" })
                    @Html.ValidationMessageFor(model => model.Highlight, "", new { @class = "text-danger" })
                </div>
                <div class="custom-checkbox custom-control">
                    @Html.EditorFor(model => model.Archive, new { htmlAttributes = new { @class = "col-sm-1 custom-control-input" } })
                    @Html.LabelFor(model => model.Archive, htmlAttributes: new { @class = "custom-control-label" })
                    @Html.ValidationMessageFor(model => model.Archive, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="position-relative row form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="mb-2 mr-2 btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '#Description',
            mode: "textareas",
            height: 400,
            //width: 600,
            plugins: "code,autolink,image,imagetools,media,link,lists,pagebreak,style,table,advhr,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,searchreplace,print,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template, wordcount, advlist, autosave, visualblocks",
            images_reuse_filename: true,
            image_title: true,
            images_upload_url: '@Url.Action("ImageUpload")',
            relative_urls: false,
        });
    </script>
}

Areas/cpanel/Views/NewsArticle/Index.cshtml
@model IEnumerable<IndianArmyWeb.Areas.cpanel.View_Models.NewsArticleIndxVM>

@{
    ViewBag.Title = "List of News Articles";
}

<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">List of News Article (s)</h5>
        <div class="pull-right">
            <a href="@Url.Action("Create","NewsArticle")" class="btn-shadow mb-3 mt-0 btn btn-primary">Create News Article</a>
        </div>
        <table class="mb-0 table table-hover table-bordered tab w-100" id="myTable">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.NewsCategory)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Headline)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PublishDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ArchiveDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Archive)
                    </th>
                    
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NewsCategory)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Headline)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PublishDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ArchiveDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Archive)
                        </td>
                        
                        <td>
                            <a href="@Url.Action("Edit", new { id = item.NewsArticleId })"><i class="fa fa-edit"></i></a>
                            <button type="button" class="btn btn-transparent red btn-xs" onclick="Delete(@item.NewsArticleId, this)"><i class="fa fa-trash"></i></button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts {
    <script>
    LoadJDT('#myTable');

    function Delete(id, event) {
        var TableId = "#myTable";
        var Jsonurl = '@Url.Action("DeleteOnConfirm")';
        DeleteJDTRow(id, event, TableId, Jsonurl)
    }
    </script>
}